### ISSUE TITLE
Blade stranger - I/O mapping problem

### ISSUE THREAD

**Issue by Ragnarok9975** [teknogods/OpenParrot#104]
Hi,
there's a problem with keyboard input mappings in Blade Stranger.
Game has some hardcoded keyboard inputs (up,down,left,right = P1 directions, A,S,Z,X = B1,2,3,4, space=START)
When you set keyboard inputs in TP UI, they can interfere with these keys. (same problem as Gouketsuji Ichizoku games).

Is it possible to prevent game EXE from reading direct keyboard inputs, and only allow inputs from TP I/O Emulator ?

**Comment by Boomslangnz** [comment]
Try it now, just pushed fix

**Comment by Ragnarok9975** [comment]
Hi,
updated my TP this morning, but problem still here...
TPUI 1.0.0.364, openparrot 1.0.0.213

**Comment by Boomslangnz** [comment]
Sorry, There was a version I didn't fix still

Just pushed fix for public ver, should be good now

**Comment by Ragnarok9975** [comment]
Thanks Boomslangnz, now it works perfectly !
Best Regards,
David
