### ISSUE TITLE
Star Wars battle pod not launching, msvcr100.dll issue 

### ISSUE THREAD

**Issue by Dutchman2000** [teknogods/OpenParrot#106]
Faulting application name: RSLauncher.exe, version: 0.0.0.0, time stamp: 0x5476de4e
Faulting module name: MSVCR100.dll, version: 10.0.40219.325, time stamp: 0x4df2bcac
Exception code: 0xc0000005
Fault offset: 0x000000000003bfbf
Faulting process id: 0x6018
Faulting application start time: 0x01d63f8798c65034
Faulting application path: D:\TeknoParrot\sw\Launcher\RSLauncher.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCR100.dll
Report Id: e8440e2c-8893-49bf-80c8-11ef314c548a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Dutchman2000** [comment]
This happens with OpenParrot64.

**Comment by Boomslangnz** [comment]
Think that's a visual runtime error

Install one of those all in one visual runtime packs

**Comment by Dutchman2000** [comment]
Installed all visual runtimes and the error continues.  Also did a fresh, clean install of Windows 10, installed all visual runtimes then teknoparrot and the error still continues.

**Comment by Dutchman2000** [comment]
When free play is unchecked, the game launches but not in full screen.  If free play is checked it crashes with the error.

**Comment by Dutchman2000** [comment]
Now I have tested a laptop as well, same issue.  Is this a problem with Windows 10 2004?

**Comment by legend800** [comment]
Works fine for me. I'm on 1903.

**Comment by Dutchman2000** [comment]
I just tested it on a third computer running Windows 10 version 2004 and it has the same error and crash.  I think the developers need to start testing on version 2004.

**Comment by Nezarn** [comment]
update to latest, should be fixed

**Comment by Dutchman2000** [comment]
Problem is fixed with the new version.  Thank you so much!
