### ISSUE TITLE
[suggestions] analog threshold for keyboard and launch games from command line?

### ISSUE THREAD

**Issue by donnaken15** [teknogods/OpenParrot#110]
Straight forward questions or suggestions with this
I'd like to play H2Overdrive with the keyboard without making almost full turns, and not plug in my controller every time I want to play, and I want to just play it immediately whenever I have the feeling to, without waiting for the launcher to do everything
and I tried opening it through whatever the launcher uses opening the OpenParrotWin32 exec but it prevents the controller from working

**Comment by donnaken15** [comment]
oh just realized the UI repo that also exists but don't know where what these suggestions are based on belong exactly

**Comment by Poliwrath** [comment]
controls are piped through the UI, there's command-line arguments for launching the UI minimized (meant for use with game launchers) if I remember correctly

**Comment by Boomslangnz** [comment]
also added analog trhreshold for keyboard awhile back. Check Use Keyboard For Axis in game settings and then modify speed you want for axis to reach full value etc

**Comment by donnaken15** [comment]
Alrighty

**Comment by donnaken15** [comment]
hm, command line stuff doesnt appear to be working, using arguments detected from [App.xaml](https://github.com/teknogods/TeknoParrotUI/blob/master/TeknoParrotUi/App.xaml.cs)
and sensitivity on keyboard wheel goes turbo after 3 seconds
