### ISSUE TITLE
Games not working from drive letter D

### ISSUE THREAD

**Issue by a7mag3ddon** [teknogods/OpenParrot#114]
King of fighters 98 match final edition for NesicaxLive and Vamipre Saviour for NesicaxLive will not boot if running from hard drive with the letter D assigned to it.

edit..
also  Battle Fantasia and Vrimson Clover

Needs some kind of redirection fix ?

**Comment by Nezarn** [comment]
Try with this build: [Link](https://ci.appveyor.com/api/buildjobs/42e8fqttfngush1v/artifacts/build%2Fbin%2Frelease%2FOpenParrotWin32.zip)
(also please check if they create any files on D:\ and also if test menu settings save\load works)

**Comment by a7mag3ddon** [comment]
Not sure if related ill have to restore from a backup but a few games are now failing to load that previously worked with errer Failed to load Dll.

Will restore and update this post if they work again

**Comment by a7mag3ddon** [comment]
Ok so yeah, i restored the openparrotwin32 and the errors for failed to open dll have stopped and games boot again.

i tested a few but can confirm 100% that Dariusburst broke, en-eins perfekwelt and Gouketsuji ichizoku  stopped working.

**Comment by a7mag3ddon** [comment]
Updated to latest TP 468 and those games are working again now so i guess youve fixed it and made a release.
