### ISSUE TITLE
No sound effects in TGM3

### ISSUE THREAD

**Issue by Formedras** [teknogods/OpenParrot#122]
Sound effects don't work in Tetris: The Grand Master 3 — Terror Instinct. Music works fine.
Tried in 1920x1080 fullscreen and 640x480 windowed.

Effects work fine in other TTX launchers, such as TypeXtra.

**Comment by ToniBC** [comment]
This error is still present, it works without problems, but the FX sounds do not, only the music is heard.

**Comment by ReaverTeknoGods** [comment]
Yes, I even tried with dsound wrapper and the FX did not work. We play Tetris a lot in office and hate this issue. Will investigate in coming weeks after new APM3 stuff is done.
