### ISSUE TITLE
Teknoparrot UI run into exeption

### ISSUE THREAD

**Issue by Raulrapadura** [teknogods/OpenParrot#129]
Hello, I´m new user in Github. 

I´m having an error when closing a runing teknoparrot game. It says that put here the exception.txt. So I copy and paste here:

System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   at TeknoParrotUi.Views.GameRunning.<CreateGameProcess>b__30_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by spaelectronics** [comment]
I have the same issue.

**Comment by dudesh34** [comment]
me also...

**Comment by Harmmmm** [comment]
Can someone give slightly more information?😅

**Comment by Harmmmm** [comment]
Which game? Do you close with ESC key or window X button? Does it happen everytime? Does it happen with multiple games? Which version of TP do you have? What windows version?

**Comment by dudesh34** [comment]
its when i try to update tekno...

**Comment by spaelectronics** [comment]
It's multiple games. A lot of them actually. 
It only happens when run from command line. 

For example, I use AttractMode and it happens when exiting the game using the ESC key. I'd more than 50% of the time, this error pops up for a split second, then disappears.

**Comment by Harmmmm** [comment]
> It's multiple games. A lot of them actually. It only happens when run from command line.
> 
> For example, I use AttractMode and it happens when exiting the game using the ESC key. I'd more than 50% of the time, this error pops up for a split second, then disappears.

Maybe attractmode tries to close the game aswell?

**Comment by Harmmmm** [comment]
> its when i try to update tekno...

That is clearly a different problem. Look in the exception text, it states this happens in the game running screen.

**Comment by spaelectronics** [comment]
As far as I know, AttractMode does not attempt to close the game. I think this is an issue with TP

**Comment by Raulrapadura** [comment]
> Can someone give slightly more information?😅

Hello. I get this error when launch the game using CMD and XML profile and close it with ESC key (I´am using BIGBOX mode of LaunchBox launcher). If I launch the game from Teknoparrot UI the error does not shows up. This happens with allmost every game, but sometimes a failing game suddenly closes without errors and in the next try fails again. I cant find any clue why.

**Comment by PolybiusExtreme** [comment]
I had the same problem and found a solution. Uncheck „Hide console windows“ in the TPUi settings. I think the issue has to do with the (hiding?) cmd window.

**Comment by PolybiusExtreme** [comment]
Yeah its fixed for some month :)
