### ISSUE TITLE
Supercars Fpsfix issue and extra

### ISSUE THREAD

**Issue by fire0128** [teknogods/OpenParrot#132]
Hi Devs, I've tested Supercars and found the following issues. The zero does not register in the pin select screen. When using the Fpsfix the menus and score screens etc run way to slowly almost unplayable but when the fix is turned off they run super fast, please could these be fixed by one of the Devs when they have time, its hugely appreciated,  thankyou

**Comment by fire0128** [comment]
Meant to say this is tested using the latest TP fully updated

**Comment by Boomslangnz** [comment]
Been fixed now thanks
