### ISSUE TITLE
Nicktoons Nitro - ingame selection screen - input issues

### ISSUE THREAD

**Issue by ghost** [teknogods/OpenParrot#133]
The menu left and menu right button should be the wheel axis, like shown in the ingame selection screen.
The gas pedal is also shown in the selection screen, but dont work.
A fix would be great :)

**Comment by cor094** [comment]
In teknoparrot, just bind menu left and menu right to your wheel. Then, bind Start to your gas pedal.

**Comment by Boomslangnz** [comment]
Been fixed now. Thanks
