### ISSUE TITLE
return the main menu in Aleste

### ISSUE THREAD

**Issue by Getze56901** [teknogods/OpenParrot#155]
when aleste just came out in teknoparrot you could access a main menu and you could pause whenever you wanted but in the last update they removed the main menu and put a somewhat uncomfortable message from the aime network I hope they solve that
before
![Screenshot_20210827_171053](https://user-images.githubusercontent.com/88003612/131193802-06924f43-d243-4e42-bb09-2dc7cd45be81.jpg)

after
![Screenshot_2021-08-27_10-16-58 (1)](https://user-images.githubusercontent.com/88003612/131194061-61eb5cb6-2785-4b27-84c0-09a3fdcfccd1.png)

**Comment by Getze56901** [comment]
I have fixed it by modifying the following line in ALESTE.XML

<ExtraParameters/> Delete -a</ExtraParameters

<GameProfileRevision>1</GameProfileRevision> 
Delete >2< and change for  >1<

**Comment by Poliwrath** [comment]
Hello, currently teknoparrot will only boot the game in "arcade mode" as it was intended. I don't know how stable the PC port version is (seemingly not very stable since I'm suddenly not able to open the game after switching a few times?), but this might be added as an option in the future.
