### ISSUE TITLE
HOD4 Ver C (TeknoParrot 1.0.0.643)

### ISSUE THREAD

**Issue by OndaCouch421** [teknogods/OpenParrot#170]
Graphics problem & Sound Problem after 3rd stage

**Comment by legend800** [comment]
You have to provide more details if you expect anything to get resolved? What's the gfx issue? What's the sound issue?

**Comment by OndaCouch421** [comment]
basically what there saying how the screen changes colors from a greyish to greenish color and the sound repeats itself after the 3-4 stage when completing the level.
