### ISSUE TITLE
wangan 5dx+(TeknoParrot 1.0.0.643)

### ISSUE THREAD

**Issue by OndaCouch421** [teknogods/OpenParrot#182]
Unable To Save Progress.

**Comment by Riddler1** [comment]
Hello, to clarify do you mean the story save progress?

I found that the car tuning upgrades saves and
the mileage saving works but there is no openprogress.sav file generated which saves thes story progress.

it seems in the WMMT5DXPlus.cpp, the code is all comnented out from lines 601

**Comment by beer19761** [comment]
i have same problem . what should i do? please...
