### ISSUE TITLE
ARM32/64 Build support for Windows

### ISSUE THREAD

**Issue by holaimscott** [teknogods/OpenParrot#204]
With the rise of ARM devices coming up, having native ARM64 support would be a great thing to consider.
This would help TeknoParrot have further compatibility with future systems, as well as being able to run in current ARM devices natively.

A lot of popular and long-time emulators [like Dolphin, Duckstation and PPSSPP](https://youtu.be/93grsZl3lHo) have native ARM support.

**Comment by EmiMidnight** [comment]
A bit of a late response but I don't think this is feasible, or at the very least useful. At this point in time 100% of the games TP supports are based on x86 or x64 hardware and thus will have to run through window's ARM conversion layer one way or the other. At best, TPUI (and not TP/OP) could get a native arm build but it would still just end up launching a traditional x64 executable, unless future games release on ARM. I think if there's ever arcade games out there that run on windows ARM we can reopen this, but until then i'm going to close this issue.
