### ISSUE TITLE
[FIX = UK/US keyboard switch ]Farcry Paradise (teknoParrot 1.0.0.804) no "trigger" with mayflash dolphinbar

### ISSUE THREAD

**Issue by Aynshe** [teknogods/OpenParrot#212]
Hi,

Farcry Paradise (teknoParrot 1.0.0.804) no "trigger" with mayflash dolphinbar but only ingame, in menu is it ok.

I have tested for with a usb adaptator bluetooth, teknoparrot detect the wiimote  "unknown device",  but works normally.

For the moment I use 1 mayflash and 1 bluetooth adapter to play two guns, the other games tested do not have this problem.

thx

**Comment by Aynshe** [comment]
> Hi,
> 
> Farcry Paradise (teknoParrot 1.0.0.804) no "trigger" with mayflash dolphinbar but only ingame, in menu is it ok.
> 
> I have tested for with a usb adaptator bluetooth, teknoparrot detect the wiimote "unknown device", but works normally.
> 
> For the moment I use 1 mayflash and 1 bluetooth adapter to play two guns, the other games tested do not have this problem.
> 
> thx

D'après un utilisateur Retrobat ayant laissé un message sur facebook, il serait possible de fix le problème en passant le "clavier en UK/US"

Je n'ai pas testé, mais un autre utilisateur le confirme.

**Comment by Aynshe** [comment]
Si il s'avère que c'est le problème, il serait intéressant de le mettre en page wiki ou bien de patcher ?

**Comment by Boomslangnz** [comment]
this should be fixed now, thanks
