### ISSUE TITLE
TeknoparrotUI ran into an exception

### ISSUE THREAD

**Issue by uurbana** [teknogods/OpenParrot#214]
I have these error since two week when I launch games.
My config : windows 11 22H2 - last AMD graphic driver
Thanks for help.

[exception.txt](https://github.com/teknogods/OpenParrot/files/10304707/exception.txt)

**Comment by nzgamer41** [comment]
![image](https://user-images.githubusercontent.com/20289640/213969183-7199a09a-66f6-4856-bb69-3fc9d4d5a45a.png)
Run TeknoParrotUI.exe as administrator.
