### ISSUE TITLE
Teknoparrot error 0x80040154

### ISSUE THREAD

**Issue by iammedude** [teknogods/OpenParrot#217]
Whenever im trying to play wmmt6, I get the error 0x80040154. I don't have any windows 7 files backed up and I'm only on windows 10 no other versions of windows.

**Comment by nzgamer41** [comment]
Closing issue, this is a windows issue and not caused by OpenParrot. If you are sure it's not your computer, take a screenshot and reply with it.

**Comment by iammedude** [comment]
![image](https://user-images.githubusercontent.com/123291431/214180338-32f07174-94dc-4028-a883-764a9be4279b.png)

**Comment by nzgamer41** [comment]
duplicate of #345

**Comment by nzgamer41** [comment]
https://github.com/teknogods/TeknoParrotUI/issues/345
