### ISSUE TITLE
Taiko no Tatsujin: Niijiro Ver. (TeknoParrot 1.0.0.922)

### ISSUE THREAD

**Issue by Arthurfogo7** [teknogods/OpenParrot#218]
https://user-images.githubusercontent.com/85951083/215284153-d73f23cd-2676-496f-adfd-376bd5f50691.mp4

It just opens and closes after I try to play, am I doing something wrong? I tried to change the dump, but it didn't change much. What should I do?

**Comment by Boomslangnz** [comment]
It appears this is quite an old post which never got answered. I apologize for that, are you still having difficulties? I tried the game just a few days ago and it worked fine 

Closing for now assuming it has been well resolved by now
