### ISSUE TITLE
Street Fighter V Type Arcade - keyboard mapping conflicting with hardcoded keys

### ISSUE THREAD

**Issue by Ragnarok9975** [teknogods/OpenParrot#220]
TeknoParrot version: 1.0.0.937

Did this issue happen with an older version: don't know

Game with issue:Street Fighter V

Detailed description of issue:  When trying to map keyboards keys, some inputs are conflicting with in-game hardcoded inputs ( a ,w s,d, arrows, etc...) - These built-in inputs should be inhibited so that only teknoparrot configured keys are used. Strangely, these keys do nothing in test mode, only in-game.

Reproduction details: map keys for P1 coin, start, button 1 and nothing else, you'll be able to move with a,w,s,d keys on caracter selection and in-game

**Comment by EmiMidnight** [comment]
This should be fixed now. Still investigating other issues with the game.
