### ISSUE TITLE
Wangan Midnight Maximum Tune 5 won't run after the updates

### ISSUE THREAD

**Issue by bluejaye** [teknogods/OpenParrot#222]
This morning there're two updates, one of the update is the OpenParrot Core DLL. 

Wangan Midnight Maximum Tune 5 cannot start after the updates, please check it out.

![image](https://user-images.githubusercontent.com/7939234/225798968-b66a13c4-fa66-47db-854b-251f7bc73438.png)

**Comment by Nezarn** [comment]
There was no update that would affect WMMT5, still an user issue.
