### ISSUE TITLE
Missing Steering Wheel on Let´s Go Safari

### ISSUE THREAD

**Issue by CCSP2294** [teknogods/OpenParrot#224]
Hi. In LGS the steering wheel does not works, XINPUT or DirectINPUT. Tested with the latest version of TeknoParrot

**Comment by OndaCouch421** [comment]
still having issues with this its on 1.0.0.1057 and ongoing

**Comment by Boomslangnz** [comment]
Hello, these issues are now all fixed. Thanks

**Comment by OndaCouch421** [comment]
Thanks a lot! Works great
