### ISSUE TITLE
"Initial D: Arcade Stage Zero ver.2" also needs "remove DVD Drive check" Mods

### ISSUE THREAD

**Issue by mame-rr-player001** [teknogods/OpenParrot#228]
It seems that not only "Initial D: Arcade Stage Zero"
but also "Initial D: Arcade Starge Zero ver.2"
needs "remove DVD Drive check" Mods
to pass the Initialize process.

I can't play this Game title.

What should I do?

**Comment by Poliwrath** [comment]
dont use segatools
