### ISSUE TITLE
Deal or No Deal Arcade - Teknoparrot 1.0.0.1073

### ISSUE THREAD

**Issue by OndaCouch421** [teknogods/OpenParrot#250]
seems to auto select if not selected in enough time. 
also is there support for the delux version of this game when running it through the same version 
basically it crashes after trying to launch from cmd.

thanks again for fixing the issues LETS GO!!!

**Comment by Poliwrath** [comment]
Stop making issues, you've been banned from the discord already + these are not reproducible, thanks.

**Comment by OndaCouch421** [comment]
Why am I banned from discord

**Comment by Poliwrath** [comment]
jackass spammer and ban evading (5+ accounts), you aren't getting unbanned

**Comment by OndaCouch421** [comment]
Dude I don't even have a fucking account in your god damn platform that is
another fucking member so fuck you

**Comment by OndaCouch421** [comment]
Go harass someone else asshole I'm here to help your stupid fucking
platform go talk to RRZ ON EMULINE AKA FRANK1 HE TALKS ALOT OF SHIT About U
GUYS HAS SEVERAL ACCOUNTS ALSO SO FUCK YOU

**Comment by OndaCouch421** [comment]
IM TIRED OF IT IM TIRED IF TRYING HELP THIS SHITTY PLATFORM IM TIRED OF U
MAKING MONEY OFF OUR VIDEOS
ANS IM TIRED IF HAVING UR COMMUNITY COMING TO MY CHANNEL ASKING FOR HELP
HANDLE UR OWN GOD DAMN ISSUES

**Comment by OndaCouch421** [comment]
Next time ask assholes I put a lot of work in helping out on my end so fuck
you and all u can do is assume what an idiot

**Comment by OndaCouch421** [comment]
Ur buddy RRZ AKA FRANK1 WHO WAS HARASSING THE DEVELOPERS IS STILL IN THE
CHAT AND IM BANNED LMAO AND HES PROBABLY ON A VPN I DONT GO ON UR Stupid
DISCORD SINCE MARCH

**Comment by OndaCouch421** [comment]
I don't wanna be apart of your money hungry project u banned the wrong
person I haven't been active in ur shitty discord for fucking months

**Comment by EmiMidnight** [comment]
May I suggest going to therapy? You clearly have issues that you need to work out.

**Comment by Poliwrath** [comment]
I mean there's 5 accounts banned with names like Gaming Onda Couch, OndaCouch Gaming, The Arcade Gamer and they all
