### ISSUE TITLE
Grid - name entry fault

### ISSUE THREAD

**Issue by Riddler1** [teknogods/OpenParrot#256]
Hi team

A change to the OpenParrot.dll file broke the ability to delete initals using the brake pedal.

Initals are entered with gas pedal but can no longer be deleted with brake pedal.
Affects both hiscore and multiplayer name entry

Was working on version 1.0.0.928
Stopped working since version 1.0.0.1082

**Comment by Boomslangnz** [comment]
Hi,

Thanks for posting this issue, I have just pushed fix for it. Please wait a few mins and then update :)

Cheers

**Comment by Riddler1** [comment]
👍
