### ISSUE TITLE
Sega Rally 3 Unable to press start after loading

### ISSUE THREAD

**Issue by Traace** [teknogods/OpenParrot#264]
**OpenParrot version**: 1.0.0.690
**Did this issue happen with an older version**: Don't know. It is my first test

**Game with issue**: Sega Rally 3

**Detailed description of issue**:
The Game does launch but I'm unable to progress after that and stuck on the screen with the yellow start button. The start button is properly mapped and working in all other games.

I tried with and without freeplay, same result.

CPU: i9-13900K
GPU: AMD RX6950 XT (24.1.1)
OS: Windows 11 23H2

**Reproduction details**:
Start the game, wait till the screen with the yellow "start" button appear. Press the button. Nothing happens.

**Any other details**: No
**Pictures of issue**: I think the text explains it well.

**Comment by Pete-McDonald** [comment]
Works fine on 1.0.0.1204 - your version is really old, you should back it up and then update

Make sure you've checked the wiki too.

CPU: i9-12900K
GPU: NVIDIA 3080Ti
OS: Windows 10 Pro 22H2

**Comment by Traace** [comment]
1.0.0.690 is the lastest offical release of openparrot... And that was picked by default in UI. No newer update is available.

shall I try teknoparrot instead?

**Comment by Pete-McDonald** [comment]
I've only ever used TeknoparrotUI to launch games, might as well try

**Comment by Cheesmaker** [comment]
Same issue here with last update. Start button don't work..

**Comment by antoniodesousa** [comment]
It works fine for me. No issues whatsoever.

TeknoParrot 1.0.0.1207
CPU: AMD Ryzen 6900HX
GPU: Radeon RX 6600 XT
OS: Windows 11 23H2

**Comment by Cheesmaker** [comment]
works fine now. no update or change done. I don't understand, it was not the controller i've tested with another game.

**Comment by Traace** [comment]
Dont know. Works again for me, too. Maybe latest UI Update fixed it. Closed 👍

**Comment by xudbux** [comment]
im still having the issue. game used to work and now the start button wont work
