### ISSUE TITLE
Lost Land Adventure : no fullscreen

### ISSUE THREAD

**Issue by scooby911** [teknogods/OpenParrot#266]
Whatever the option (fullscreen or windowed bordeless), Lost Land Adventure does not go to fullscreen.

Config:
CPU: i5-10500K
GPU: Nividia 1080
OS: Windows 10 22H2

**Comment by marcosgaming10** [comment]
Hi, not yet. Have you fix this game for to have it in Full Screen? I would play with my light guns ;)

**Comment by marcosgaming10** [comment]
Tomorrow i will try with borderless gaming...

**Comment by Georgie-SBH** [comment]
Had this same issue, tried another dump and works great now in borderless fullscreen. Maybe you have a bad dump as well.

**Comment by marcosgaming10** [comment]
> Had this same issue, tried another dump and works great now in borderless fullscreen. Maybe you have a bad dump as well.

Hi, thanks.
Can you write me in private to mctrading2018 at Gmail com
Thanks.

**Comment by jonny555** [comment]
Lost land adventure restarts on first level 
Also doesn't allow sinden border to display as soon as the screens other than gameplay sinden border drops behind

**Comment by Boomslangnz** [comment]
borderless fullscreen option should work on this now
