### ISSUE TITLE
Pokken Tournament - Incorrect Input for B button and Y button

### ISSUE THREAD

**Issue by Atlint4688** [teknogods/OpenParrot#267]
Hi,I'm playing older versions of Pokken for research purposes and noticed the B button and Y button are incorrectly mapped for versions below 24.

B button presses both A and B buttons : 
![image](https://github.com/teknogods/OpenParrot/assets/132469796/1063e351-f602-45c5-866c-861fedf9eb87)

Y button presses both Y and B buttons:
![image](https://github.com/teknogods/OpenParrot/assets/132469796/d149f40c-451d-4960-9f1b-b02635c075d7)

Tested with 01,02,03,13,16,20,23,24 on OpenParrotx64 1.0.0.690 on keyboard with directinput.

**Comment by Boomslangnz** [comment]
I'm afraid without having access to old versions, we cannot make any changes here. I tested on build here and inputs worked fine on dinput using keyboard. We can revisit if we can get these builds at a later date
