### ISSUE TITLE
Issues with DirectInput on Elevator Action Death Parade and Gundam Spirits of Zeon

### ISSUE THREAD

**Issue by zenaro147** [teknogods/OpenParrot#281]
The controller simply doesn't work at all... it works with RawInput.
The same issue happens with Gundam Spirits of Zeon
Other games works fine

**Comment by Boomslangnz** [comment]
Hi! I Apologize for the late reply

 I spent the past hour tracking down why direct input wouldn't work on EADP and finally solved the issue, tricky one to find!

Gundam Spirits of Zeon was fixed recently too :)

Thanks for reporting this issue
