### ISSUE TITLE
Operation G.H.O.S.T  no crosshair

### ISSUE THREAD

**Issue by wei134102** [teknogods/OpenParrot#283]
hi  i am a newer
Operation G.H.O.S.T  no crosshair
the question is above ,i can play the game ,but i cant see the p1 and p2 crosshair in the srceen.
![054c2a2255335d2df69b072bedf8ddd](https://github.com/teknogods/OpenParrot/assets/69394172/50e95d95-699e-4f8a-8863-d676d27f593a)

this is my gamefile list:
![Uploading 2d1e5ad10fad601d6083994fc8bf155.jpg…]()

**Comment by marcosgaming10** [comment]
Same problem !!! I don't kno why

**Comment by cor094** [comment]
It's because you have downloaded a version of the game where someone has patched out the crosshair. Use a clean game dump and you will have crosshairs.

**Comment by marcosgaming10** [comment]
I have download all collection teknoparrot from archive. I think are dump clean. Please help me. I would fix this.

**Comment by cor094** [comment]
> I have download all collection teknoparrot from archive. I think are dump clean. Please help me. I would fix this.

Send me a message on Discord (same username) and I'll help you undo the "no crosshair" patch you are using.

**Comment by Nezarn** [comment]
Closing since its not an issue + piracy talks
