### ISSUE TITLE
Add support for WMMT6RR

### ISSUE THREAD

**Issue by jcstahl1** [teknogods/OpenParrot#288]
Please add support for Wangan Midnight Maximum Tune 6 RR.  The public dump has been available for a while.  Files are available for standalone play but TP UI support would make it so much better for configuring controls, possible online play, etc.  Thanks for everything you all do for the arcade gaming community!

**Comment by Boomslangnz** [comment]
Hi, we understand but I believe current developers have no interest in working on WMMT6RR currently, Feel free to add support via OpenParrot however which is our open source part of TeknoParrot :)

Thanks
