### ISSUE TITLE
Dead Heat does not work with output blaster.

### ISSUE THREAD

**Issue by ShinobiMega** [teknogods/OpenParrot#289]
Hello, the free for ALL version is not working output blaster, I put the dll and enabled output in tk, but before starting the game, I receive a message that it is not compatible Why was it previously compatible and now it is no longer, would there be a solution I would like to thank everyone for their availability and space for questions, problems and compliments. 
![image](https://github.com/user-attachments/assets/1daed32a-16e2-4d02-860c-59499fb0c8b5)

**Comment by Boomslangnz** [comment]
I don't know where you are getting that error from even, Output Blaster, TeknoParrot & TeknoParrotUI do not have any messagebox errors like you are recieving. Can you ensure you download from my official github? https://github.com/Boomslangnz/OutputBlaster/releases

**Comment by Boomslangnz** [comment]
just tested with my latest release and works fine

**Comment by ShinobiMega** [comment]
![image](https://github.com/user-attachments/assets/7d5de5dc-99ba-43b0-87ac-a0a8d0971fbf)
I placed the outputblaster files in the C:\TeknoParrot\ElfLdr2 folder

and when I start the game the bland game screen appears, then the output blaster not supported window appears, in the teknoparrot cmd, it shows outputblaster loaded!.. but then this window appears.
I'm using Windows 10.

I'm using your official version of github output 1.0 and the latest version of the teknoparrot loader

**Comment by Boomslangnz** [comment]
ah I see

ok so version you were using didn't have support for Dead Heat outputs hence the error. That MessageBox error has actually been removed on newer code hence why I did not understand

I have pushed a new version just now

https://github.com/Boomslangnz/OutputBlaster/releases

Version 0.11 should resolve :)

**Comment by ShinobiMega** [comment]
Great job, working perfectly, thanks for your great work..
