### ISSUE TITLE
xinput Y axis for player 2 is inverted in some games.

### ISSUE THREAD

**Issue by Trihy** [teknogods/OpenParrot#309]
I been experiencing this problem since many months. Can't remember if worked fine in older builds.

For some games, xinput for player 2 Y axis is inverted.

ie. Target terror, Jurassic park. Probably some others.

I couldn't find any solution. In game test menu calibration doesn't help.

Other games like all hotd, transformers and many others doesn't have this problem.

**Comment by Boomslangnz** [comment]
Hi, thanks for letting us know. I just pushed fix for a few games I could find with this issue. Let us know if we have missed any

Cheers!

**Comment by Trihy** [comment]
Hi. Thanks. Working fine now. Will report if find more games with this problem.

BTW will be nice some day to be able to map more than one xinput per action. I mean for some games like transformers shadow rising or any other with "special action button". So those buttons can be mapped for both players.

**Comment by Boomslangnz** [comment]
Yeah hopefully we can add some day 

thanks

**Comment by Trihy** [comment]
Hi. I found Ghostbusters is also inverted for player 2.

**Comment by Boomslangnz** [comment]
Pushed fix for inverted aim on P2

Will need others to mention coin issue before I push fix there

**Comment by Trihy** [comment]
Vampire night has the original problem reported here, Y axis is iverted, up goes down, down goes up for xinpunt both players.
