### ISSUE TITLE
GRID controls get very laggy

### ISSUE THREAD

**Issue by spazzy89** [teknogods/OpenParrot#40]
Hi, not sure what version this began happening in because I just installed the game, but the GRID controls become quite sticky. E.g. if I keep hitting and letting go of gas, it generally starts out fine but then seemingly randomly the gas gets stuck at various levels. This happens with the steering wheel axis as well, so the car keeps going in a direction when I've tried to get it to turn the other way. I've had the delay sometimes occur for up to ~1/4 to ~1/3 of a second in the worst cases.

**Comment by Poliwrath** [comment]
Should be fixed already (since nov 2019)
