### ISSUE TITLE
Error 6401 I/O Transformers Human Aliance

### ISSUE THREAD

**Issue by jhonipin** [teknogods/OpenParrot#74]
I'm having this error when trying to play this game with two x360 joystck, when loading the game everything works perfectly more than at certain times of the game happens the error 6401 tried everything else solves now I don't know if this error is from demulshooter or the tecknoparrot

**Comment by Poliwrath** [comment]
If this still happens on latest, please report it at https://github.com/teknogods/teknoparrot-issues/issues (because it's not a OpenParrot game)
