### ISSUE TITLE
TTX2 bookeeping redirection

### ISSUE THREAD

**Issue by rufotheone-fr** [teknogods/OpenParrot#75]
Those games need a redirection for bookkeeping:

- **Gouketsuji Ichizoku: Senzo Kuyou** = Bookkeeping in folder D:\save
- **King of Fighters XII, The** = Bookkeeping in folder D:\7a6c774eb36d1ac77ea6ba146bc244c7_### (where # is an incremental number) but Test Mode creates an infinite number of folders
- Senko no Ronde: DUO - Dis-United Order = Bookkeeping in folder D:\0bd4d39aff8d7219f92f72451f642c2f_### (where # is an incremental number) but Test Mode creates an infinite number of folders.
- **Street Fighter IV** = Bookkeeping in D:/bookkeeping_yyyymmddhhmmss.bkd - D:/config_yyyymmddhhmmss.dat -
D:/localscore_yyyymmddhhmmss.rnk - D:/localtime_yyyymmddhhmmss.rnk - D:/localwins_yyyymmddhhmmss.rnk
- **Super Street Fighter IV: Arcade Edition** & **(Export)** & **Ver. 2012 (1.1)** = Bookkeeping in D:/bookkeeping_yyyymmddhhmmss.bkd - D:/config_yyyymmddhhmmss.dat -
D:/Eventlog_yyyymmddhhmmss.eld - D:/localscore_yyyymmddhhmmss.rnk)
- **Wacky Races** = Bookkeeping in the same folder as the game folder (WR0.CFG / WR0.CRC / WR1.CFG / WR1.CRC)

**Comment by zaphod77** [comment]
* Tetris The Grand Master 3:Terror-Instinct= folder D:\TGM3  sramdata folder is created by game inside there, with account data, game settings, bookeeping, and high scores all written to files there.
