### ISSUE TITLE
mouse not working or not recognize when fullscreen

### ISSUE THREAD

**Issue by ginzu2077** [teknogods/OpenParrot#81]
Hello Team!

great work as usual! Rambo is fantastic!

but since  a while now, we have this problem of mouse that is not take in charge when we play the games in fullscreen.

the only thing we can do is starting the game in windowed mode. then relauching the game in fullscreen mode.

sometimes, even after having doing that, ther problem goes on again.

problem occurs as much on win10 as win7.

thx for your help!

**Comment by Catarax** [comment]
You can wait DemulShooter to have support for this on fullscreen with a lightgun on PC.
Else you can use this tip : run Rambo windowded then, with Borderless Gaming you maximize the Rambo window and you should be able to play in fullscreen without the mouse bug.

**Comment by ginzu2077** [comment]
Thank you, but I already do that.
Unfortunately, it create an offset between the target and the real aim. 
Try from your side you will by yourself.

**Comment by ginzu2077** [comment]
OK, it' good now!
The last tp update include the fix regarding lindbergh games. 
Good job team!
