### ISSUE TITLE
Luigi's Mansion textures bug

### ISSUE THREAD

**Issue by ginzu2077** [teknogods/OpenParrot#86]
Hello,
 Someone ask me to open an issue for this game. 
I copy/past his request:

Hello I wanted to report this bug for this game.
There are other forum members who have the same graphics bug we are on windows 7 64bits

I don't think this bug is related to Windows 7 or Windows 10 version.

On my PC, the game has already worked correctly only 2 times.

But since each launch I have the graphic bug as on the attached image (textures and graphics missing) but the game remains playable.

https://image.noelshack.com/fichiers/2020/04/6/1579907736-sans-titre.jpg

I don't know if it is possible to find a solution in Teknoparrot for this game.

Apart from this bug the game works very well

**Comment by Poliwrath** [comment]
For TP issues, please report them here: https://github.com/teknogods/teknoparrot-issues/issues
This issue tracker is for OpenParrot

**Comment by ginzu2077** [comment]
OK done, thx
