### ISSUE TITLE
Brake not mapped in Batman Arcade

### ISSUE THREAD

**Issue by ruiner9** [teknogods/OpenParrot#91]
This can be confirmed by mapping the brake in the TPUI config, entering the game, then using the home key to access the test menu. Using Page Up and Page Down, with the Home key as the enter button, select Advanced Utilities and Raw Input. The other mapped buttons will register with onscreen values, the brake will not.

![image0](https://user-images.githubusercontent.com/37946113/76757438-f5b32800-675d-11ea-9ac4-e91adc01381a.jpg)

**Comment by Poliwrath** [comment]
should be working now, please reopen this if it isn't
