### ISSUE TITLE
New iDmacDrv32.dll not working with Ultra Street Fighter

### ISSUE THREAD

**Issue by triker76** [teknogods/OpenParrot#94]
with the new iDmacDrv32.dll the Game does work.
I have replaced the iDmacDrv32.dll 74kb with an old one with 68kb in OpenParrotWin32 and the Game woks fine.

**Comment by MrMiguardi** [comment]
This Issue happens to me with most of the NESiCA games, i have to replace the "iDmacDrv32.dll" file in Openparrot folder with the old 68kb file.
Basically for me 90% of the NESiCA games are actually broken.

**Comment by Nezarn** [comment]
Known issue, we are working on a fix.

**Comment by Nezarn** [comment]
added workaround, now it should work (don't forget to remove iDmacDrv dll from game folder so openparrot can copy the new one in.
